# -*- mode: makefile; -*-
#
# Makefile for fsvn (Meadow)
#

include VERSION

TAR	= tar
RM	= /bin/rm -f

EMACS	= /cygdrive/c/usr/local/Meadow-dev/bin/Meadow.exe

CONFIG  = MAKE-CFG.el.mw32

FLAGS   = -batch -q -no-site-file -l fsvn-make.el

GOMI	= *.elc *~

ARCHIVE_DIR_PREFIX = ..

include MAKE-TARGETS
