# -*- mode: makefile; -*-
#
# Makefile for fsvn (NTEmacs)
#

include VERSION

TAR	= tar
RM	= /bin/rm -f

EMACS	= /cygdrive/c/usr/local/NTEmacs/22.2/bin/emacs.exe

CONFIG  = MAKE-CFG.el.nt

FLAGS   = -batch -q -no-site-file -l fsvn-make.el

GOMI	= *.elc *~

ARCHIVE_DIR_PREFIX = ..

include MAKE-TARGETS
