# -*- mode: makefile; -*-
#
# Makefile for fsvn
#

TAR	= tar
RM	= /bin/rm -f

EMACS	= emacs-current

CONFIG  = MAKE-CFG.el

FLAGS   = -batch -q -no-site-file -l fsvn-make.el

CHECKFLAGS   = $(FLAGS)

GOMI	= *.elc *~

ARCHIVE_DIR_PREFIX = ..

include MAKE-TARGETS.mk

